### ISSUE TITLE
Cannot install via npm

### ISSUE THREAD

**Issue by jusopi** [darkoverlordofdata/ash.coffee#1]
It seems that despite the npmjs.org stating that there are no dependencies for this package, it throws errors around bower (which baffles me because a) all I'm trying to do is utilize the resource in my node project via `ash = require 'ash.coffee'` and b) the whole point of trying to install this via npm is because I am developing this in a CommonJS usage paradigm)

Here is the CL Error output when running `npm i ash.coffee --save`

```
sh: bower-installer: command not found

npm ERR! ash.coffee@0.1.0 get: `bower-installer`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the ash.coffee@0.1.0 get script.
npm ERR! This is most likely a problem with the ash.coffee package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower-installer
npm ERR! You can get their info via:
npm ERR!     npm owner ls ash.coffee
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.4.0
npm ERR! command "/Users/jopitz/.brews/nvm/v0.10.33/bin/node" "/Users/jopitz/.brews/nvm/v0.10.33/bin/npm" "run" "get"
npm ERR! cwd /Users/jopitz/Dev/Workspaces/jusopi/ds2d-js/node_modules/ash.coffee
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jopitz/Dev/Workspaces/jusopi/ds2d-js/node_modules/ash.coffee/npm-debug.log
npm ERR! not ok code 0

npm ERR! ash.coffee@0.1.0 postinstall: `bower install && npm run get`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ash.coffee@0.1.0 postinstall script.
npm ERR! This is most likely a problem with the ash.coffee package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install && npm run get
npm ERR! You can get their info via:
npm ERR!     npm owner ls ash.coffee
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.4.0
npm ERR! command "/Users/jopitz/.brews/nvm/v0.10.33/bin/node" "/Users/jopitz/.brews/nvm/v0.10.33/bin/npm" "i" "ash.coffee" "--save"
npm ERR! cwd /Users/jopitz/Dev/Workspaces/jusopi/ds2d-js
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

It makes mention of checking the `/node_modules/ash.coffee/npm-debug.log` however because it doesn't ever complete the install, this gets removed or is never created due to the install failure.

**Comment by darkoverlordofdata** [comment]
Sorry about that. I've change the project structure recently, and it looks
like I've broken the npm install.
Question-
Are you just installing this way because my instructions said to, or is it
because npm is your preferred way to consume libraries?

I overlooked testing that because I've actually stopped using it that way
myself, I find bower fits my pipeline better. But if you prefer npm i'll
address that as the fix.
If you don't prefer npm and like using bower, I'll fix the instructions :)

On Thu, Oct 1, 2015 at 12:51 PM, jusopi notifications@github.com wrote:

> It seems that despite the npmjs.org stating that there are no
> dependencies for this package, it throws errors around bower (which baffles
> me because all I'm trying to do is utilize the resource in my node project
> via ash = require 'ash.coffee')
> 
> Here is the CL Error output when running npm i ash.coffee --save
> 
> sh: bower-installer: command not found
> 
> npm ERR! ash.coffee@0.1.0 get: `bower-installer`
> npm ERR! Exit status 127
> npm ERR!
> npm ERR! Failed at the ash.coffee@0.1.0 get script.
> npm ERR! This is most likely a problem with the ash.coffee package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     bower-installer
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls ash.coffee
> npm ERR! There is likely additional logging output above.
> npm ERR! System Darwin 14.4.0
> npm ERR! command "/Users/jopitz/.brews/nvm/v0.10.33/bin/node" "/Users/jopitz/.brews/nvm/v0.10.33/bin/npm" "run" "get"
> npm ERR! cwd /Users/jopitz/Dev/Workspaces/jusopi/ds2d-js/node_modules/ash.coffee
> npm ERR! node -v v0.10.33
> npm ERR! npm -v 1.4.28
> npm ERR! code ELIFECYCLE
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /Users/jopitz/Dev/Workspaces/jusopi/ds2d-js/node_modules/ash.coffee/npm-debug.log
> npm ERR! not ok code 0
> 
> npm ERR! ash.coffee@0.1.0 postinstall: `bower install && npm run get`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ash.coffee@0.1.0 postinstall script.
> npm ERR! This is most likely a problem with the ash.coffee package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     bower install && npm run get
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls ash.coffee
> npm ERR! There is likely additional logging output above.
> npm ERR! System Darwin 14.4.0
> npm ERR! command "/Users/jopitz/.brews/nvm/v0.10.33/bin/node" "/Users/jopitz/.brews/nvm/v0.10.33/bin/npm" "i" "ash.coffee" "--save"
> npm ERR! cwd /Users/jopitz/Dev/Workspaces/jusopi/ds2d-js
> npm ERR! node -v v0.10.33
> npm ERR! npm -v 1.4.28
> npm ERR! code ELIFECYCLE
> npm ERR! not ok code 0
> 
> It makes mention of checking the /node_modules/ash.coffee/npm-debug.log
> however because it doesn't ever complete the install, this gets removed or
> is never created due to the install failure.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darkoverlordofdata/ash.coffee/issues/1.

## 

Bruce Davidson
Schedule a meeting: https://meetin.gs/meet/bruce-davidson

**Comment by darkoverlordofdata** [comment]
npm install should be working. 
The breaking change turned out to be a post build step for the new travis build status indicator.
Now travis shows a broken status. I need to fix that but you should be good to go.

**Comment by jusopi** [comment]
To answer your question, I prefer npm and a _CommonJs_ approach for most of my development endeavors.  I found your project on npmjs.org, that's why I assumed you were targeting a more _CommonJs_ approach.  Glad to see it's fixed.  Just curious, did you push the update to npmjs.org via the `npm publish`?

**Comment by jusopi** [comment]
Thanks for the fix!

**Comment by darkoverlordofdata** [comment]
It finally showed up in npm. Thanks for the feedback.
I'm trying to be agnostic and support UMD:  RequireJS/CommonJS/global.
I find I prefer CommonJS & Browserify for business apps, and global &
closure-compiler for games.
And sometimes, I get confused between the 2 :)

On Thu, Oct 1, 2015 at 6:57 PM, jusopi notifications@github.com wrote:

> Thanks for the fix!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darkoverlordofdata/ash.coffee/issues/1#issuecomment-144897918
> .

## 

Bruce Davidson
Schedule a meeting: https://meetin.gs/meet/bruce-davidson
